services:
  - type: web
    name: multilingual-video-call
    env: node
    plan: free

    buildCommand: |
      cd client && npm install && npm run build
      cd ../backend && npm install

    startCommand: node server.js

    envVars:
      - key: NODE_ENV
        value: production

    rootDir: backend
